		if(mlen>=5 &&
			assigns[73]==l_False &&
			assigns[74]==l_False &&
			assigns[75]==l_False &&
			assigns[76]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(73, false));
			out_learnts.last().push(mkLit(74, false));
			out_learnts.last().push(mkLit(75, false));
			out_learnts.last().push(mkLit(76, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=6 &&
			assigns[77]==l_False &&
			assigns[78]==l_False &&
			assigns[79]==l_False &&
			assigns[80]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(77, false));
			out_learnts.last().push(mkLit(78, false));
			out_learnts.last().push(mkLit(79, false));
			out_learnts.last().push(mkLit(80, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=7 &&
			assigns[81]==l_False &&
			assigns[82]==l_False &&
			assigns[83]==l_False &&
			assigns[84]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(81, false));
			out_learnts.last().push(mkLit(82, false));
			out_learnts.last().push(mkLit(83, false));
			out_learnts.last().push(mkLit(84, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=8 &&
			assigns[85]==l_False &&
			assigns[86]==l_False &&
			assigns[87]==l_False &&
			assigns[88]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(85, false));
			out_learnts.last().push(mkLit(86, false));
			out_learnts.last().push(mkLit(87, false));
			out_learnts.last().push(mkLit(88, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=8 &&
			assigns[222]==l_False &&
			assigns[223]==l_False &&
			assigns[224]==l_False &&
			assigns[225]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(222, false));
			out_learnts.last().push(mkLit(223, false));
			out_learnts.last().push(mkLit(224, false));
			out_learnts.last().push(mkLit(225, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=9 &&
			assigns[89]==l_False &&
			assigns[90]==l_False &&
			assigns[91]==l_False &&
			assigns[92]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(89, false));
			out_learnts.last().push(mkLit(90, false));
			out_learnts.last().push(mkLit(91, false));
			out_learnts.last().push(mkLit(92, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=9 &&
			assigns[226]==l_False &&
			assigns[227]==l_False &&
			assigns[228]==l_False &&
			assigns[229]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(226, false));
			out_learnts.last().push(mkLit(227, false));
			out_learnts.last().push(mkLit(228, false));
			out_learnts.last().push(mkLit(229, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=10 &&
			assigns[93]==l_False &&
			assigns[94]==l_False &&
			assigns[95]==l_False &&
			assigns[96]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(93, false));
			out_learnts.last().push(mkLit(94, false));
			out_learnts.last().push(mkLit(95, false));
			out_learnts.last().push(mkLit(96, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=10 &&
			assigns[230]==l_False &&
			assigns[231]==l_False &&
			assigns[232]==l_False &&
			assigns[233]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(230, false));
			out_learnts.last().push(mkLit(231, false));
			out_learnts.last().push(mkLit(232, false));
			out_learnts.last().push(mkLit(233, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=11 &&
			assigns[97]==l_False &&
			assigns[98]==l_False &&
			assigns[99]==l_False &&
			assigns[100]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(97, false));
			out_learnts.last().push(mkLit(98, false));
			out_learnts.last().push(mkLit(99, false));
			out_learnts.last().push(mkLit(100, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=11 &&
			assigns[234]==l_False &&
			assigns[235]==l_False &&
			assigns[236]==l_False &&
			assigns[237]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(234, false));
			out_learnts.last().push(mkLit(235, false));
			out_learnts.last().push(mkLit(236, false));
			out_learnts.last().push(mkLit(237, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=11 &&
			assigns[378]==l_False &&
			assigns[379]==l_False &&
			assigns[380]==l_False &&
			assigns[381]==l_False &&
			assigns[382]==l_False &&
			assigns[383]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(378, false));
			out_learnts.last().push(mkLit(379, false));
			out_learnts.last().push(mkLit(380, false));
			out_learnts.last().push(mkLit(381, false));
			out_learnts.last().push(mkLit(382, false));
			out_learnts.last().push(mkLit(383, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=12 &&
			assigns[101]==l_False &&
			assigns[102]==l_False &&
			assigns[103]==l_False &&
			assigns[104]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(101, false));
			out_learnts.last().push(mkLit(102, false));
			out_learnts.last().push(mkLit(103, false));
			out_learnts.last().push(mkLit(104, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=12 &&
			assigns[238]==l_False &&
			assigns[239]==l_False &&
			assigns[240]==l_False &&
			assigns[241]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(238, false));
			out_learnts.last().push(mkLit(239, false));
			out_learnts.last().push(mkLit(240, false));
			out_learnts.last().push(mkLit(241, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=12 &&
			assigns[384]==l_False &&
			assigns[385]==l_False &&
			assigns[386]==l_False &&
			assigns[387]==l_False &&
			assigns[388]==l_False &&
			assigns[389]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(384, false));
			out_learnts.last().push(mkLit(385, false));
			out_learnts.last().push(mkLit(386, false));
			out_learnts.last().push(mkLit(387, false));
			out_learnts.last().push(mkLit(388, false));
			out_learnts.last().push(mkLit(389, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=13 &&
			assigns[105]==l_False &&
			assigns[106]==l_False &&
			assigns[107]==l_False &&
			assigns[108]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(105, false));
			out_learnts.last().push(mkLit(106, false));
			out_learnts.last().push(mkLit(107, false));
			out_learnts.last().push(mkLit(108, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=13 &&
			assigns[242]==l_False &&
			assigns[243]==l_False &&
			assigns[244]==l_False &&
			assigns[245]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(242, false));
			out_learnts.last().push(mkLit(243, false));
			out_learnts.last().push(mkLit(244, false));
			out_learnts.last().push(mkLit(245, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=13 &&
			assigns[390]==l_False &&
			assigns[391]==l_False &&
			assigns[392]==l_False &&
			assigns[393]==l_False &&
			assigns[394]==l_False &&
			assigns[395]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(390, false));
			out_learnts.last().push(mkLit(391, false));
			out_learnts.last().push(mkLit(392, false));
			out_learnts.last().push(mkLit(393, false));
			out_learnts.last().push(mkLit(394, false));
			out_learnts.last().push(mkLit(395, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=14 &&
			assigns[109]==l_False &&
			assigns[110]==l_False &&
			assigns[111]==l_False &&
			assigns[112]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(109, false));
			out_learnts.last().push(mkLit(110, false));
			out_learnts.last().push(mkLit(111, false));
			out_learnts.last().push(mkLit(112, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=14 &&
			assigns[246]==l_False &&
			assigns[247]==l_False &&
			assigns[248]==l_False &&
			assigns[249]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(246, false));
			out_learnts.last().push(mkLit(247, false));
			out_learnts.last().push(mkLit(248, false));
			out_learnts.last().push(mkLit(249, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=14 &&
			assigns[396]==l_False &&
			assigns[397]==l_False &&
			assigns[398]==l_False &&
			assigns[399]==l_False &&
			assigns[400]==l_False &&
			assigns[401]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(396, false));
			out_learnts.last().push(mkLit(397, false));
			out_learnts.last().push(mkLit(398, false));
			out_learnts.last().push(mkLit(399, false));
			out_learnts.last().push(mkLit(400, false));
			out_learnts.last().push(mkLit(401, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=14 &&
			assigns[567]==l_False &&
			assigns[568]==l_False &&
			assigns[569]==l_False &&
			assigns[570]==l_False &&
			assigns[571]==l_False &&
			assigns[572]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(567, false));
			out_learnts.last().push(mkLit(568, false));
			out_learnts.last().push(mkLit(569, false));
			out_learnts.last().push(mkLit(570, false));
			out_learnts.last().push(mkLit(571, false));
			out_learnts.last().push(mkLit(572, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=15 &&
			assigns[113]==l_False &&
			assigns[114]==l_False &&
			assigns[115]==l_False &&
			assigns[116]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(113, false));
			out_learnts.last().push(mkLit(114, false));
			out_learnts.last().push(mkLit(115, false));
			out_learnts.last().push(mkLit(116, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=15 &&
			assigns[250]==l_False &&
			assigns[251]==l_False &&
			assigns[252]==l_False &&
			assigns[253]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(250, false));
			out_learnts.last().push(mkLit(251, false));
			out_learnts.last().push(mkLit(252, false));
			out_learnts.last().push(mkLit(253, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=15 &&
			assigns[402]==l_False &&
			assigns[403]==l_False &&
			assigns[404]==l_False &&
			assigns[405]==l_False &&
			assigns[406]==l_False &&
			assigns[407]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(402, false));
			out_learnts.last().push(mkLit(403, false));
			out_learnts.last().push(mkLit(404, false));
			out_learnts.last().push(mkLit(405, false));
			out_learnts.last().push(mkLit(406, false));
			out_learnts.last().push(mkLit(407, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=15 &&
			assigns[573]==l_False &&
			assigns[574]==l_False &&
			assigns[575]==l_False &&
			assigns[576]==l_False &&
			assigns[577]==l_False &&
			assigns[578]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(573, false));
			out_learnts.last().push(mkLit(574, false));
			out_learnts.last().push(mkLit(575, false));
			out_learnts.last().push(mkLit(576, false));
			out_learnts.last().push(mkLit(577, false));
			out_learnts.last().push(mkLit(578, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=16 &&
			assigns[117]==l_False &&
			assigns[118]==l_False &&
			assigns[119]==l_False &&
			assigns[120]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(117, false));
			out_learnts.last().push(mkLit(118, false));
			out_learnts.last().push(mkLit(119, false));
			out_learnts.last().push(mkLit(120, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=16 &&
			assigns[254]==l_False &&
			assigns[255]==l_False &&
			assigns[256]==l_False &&
			assigns[257]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(254, false));
			out_learnts.last().push(mkLit(255, false));
			out_learnts.last().push(mkLit(256, false));
			out_learnts.last().push(mkLit(257, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=16 &&
			assigns[408]==l_False &&
			assigns[409]==l_False &&
			assigns[410]==l_False &&
			assigns[411]==l_False &&
			assigns[412]==l_False &&
			assigns[413]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(408, false));
			out_learnts.last().push(mkLit(409, false));
			out_learnts.last().push(mkLit(410, false));
			out_learnts.last().push(mkLit(411, false));
			out_learnts.last().push(mkLit(412, false));
			out_learnts.last().push(mkLit(413, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=16 &&
			assigns[579]==l_False &&
			assigns[580]==l_False &&
			assigns[581]==l_False &&
			assigns[582]==l_False &&
			assigns[583]==l_False &&
			assigns[584]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(579, false));
			out_learnts.last().push(mkLit(580, false));
			out_learnts.last().push(mkLit(581, false));
			out_learnts.last().push(mkLit(582, false));
			out_learnts.last().push(mkLit(583, false));
			out_learnts.last().push(mkLit(584, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=17 &&
			assigns[121]==l_False &&
			assigns[122]==l_False &&
			assigns[123]==l_False &&
			assigns[124]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(121, false));
			out_learnts.last().push(mkLit(122, false));
			out_learnts.last().push(mkLit(123, false));
			out_learnts.last().push(mkLit(124, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=17 &&
			assigns[258]==l_False &&
			assigns[259]==l_False &&
			assigns[260]==l_False &&
			assigns[261]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(258, false));
			out_learnts.last().push(mkLit(259, false));
			out_learnts.last().push(mkLit(260, false));
			out_learnts.last().push(mkLit(261, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=17 &&
			assigns[414]==l_False &&
			assigns[415]==l_False &&
			assigns[416]==l_False &&
			assigns[417]==l_False &&
			assigns[418]==l_False &&
			assigns[419]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(414, false));
			out_learnts.last().push(mkLit(415, false));
			out_learnts.last().push(mkLit(416, false));
			out_learnts.last().push(mkLit(417, false));
			out_learnts.last().push(mkLit(418, false));
			out_learnts.last().push(mkLit(419, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=17 &&
			assigns[585]==l_False &&
			assigns[586]==l_False &&
			assigns[587]==l_False &&
			assigns[588]==l_False &&
			assigns[589]==l_False &&
			assigns[590]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(585, false));
			out_learnts.last().push(mkLit(586, false));
			out_learnts.last().push(mkLit(587, false));
			out_learnts.last().push(mkLit(588, false));
			out_learnts.last().push(mkLit(589, false));
			out_learnts.last().push(mkLit(590, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=17 &&
			assigns[733]==l_False &&
			assigns[734]==l_False &&
			assigns[735]==l_False &&
			assigns[736]==l_False &&
			assigns[737]==l_False &&
			assigns[738]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(733, false));
			out_learnts.last().push(mkLit(734, false));
			out_learnts.last().push(mkLit(735, false));
			out_learnts.last().push(mkLit(736, false));
			out_learnts.last().push(mkLit(737, false));
			out_learnts.last().push(mkLit(738, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=18 &&
			assigns[125]==l_False &&
			assigns[126]==l_False &&
			assigns[127]==l_False &&
			assigns[128]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(125, false));
			out_learnts.last().push(mkLit(126, false));
			out_learnts.last().push(mkLit(127, false));
			out_learnts.last().push(mkLit(128, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=18 &&
			assigns[262]==l_False &&
			assigns[263]==l_False &&
			assigns[264]==l_False &&
			assigns[265]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(262, false));
			out_learnts.last().push(mkLit(263, false));
			out_learnts.last().push(mkLit(264, false));
			out_learnts.last().push(mkLit(265, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=18 &&
			assigns[420]==l_False &&
			assigns[421]==l_False &&
			assigns[422]==l_False &&
			assigns[423]==l_False &&
			assigns[424]==l_False &&
			assigns[425]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(420, false));
			out_learnts.last().push(mkLit(421, false));
			out_learnts.last().push(mkLit(422, false));
			out_learnts.last().push(mkLit(423, false));
			out_learnts.last().push(mkLit(424, false));
			out_learnts.last().push(mkLit(425, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=18 &&
			assigns[591]==l_False &&
			assigns[592]==l_False &&
			assigns[593]==l_False &&
			assigns[594]==l_False &&
			assigns[595]==l_False &&
			assigns[596]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(591, false));
			out_learnts.last().push(mkLit(592, false));
			out_learnts.last().push(mkLit(593, false));
			out_learnts.last().push(mkLit(594, false));
			out_learnts.last().push(mkLit(595, false));
			out_learnts.last().push(mkLit(596, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=18 &&
			assigns[739]==l_False &&
			assigns[740]==l_False &&
			assigns[741]==l_False &&
			assigns[742]==l_False &&
			assigns[743]==l_False &&
			assigns[744]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(739, false));
			out_learnts.last().push(mkLit(740, false));
			out_learnts.last().push(mkLit(741, false));
			out_learnts.last().push(mkLit(742, false));
			out_learnts.last().push(mkLit(743, false));
			out_learnts.last().push(mkLit(744, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=19 &&
			assigns[129]==l_False &&
			assigns[130]==l_False &&
			assigns[131]==l_False &&
			assigns[132]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(129, false));
			out_learnts.last().push(mkLit(130, false));
			out_learnts.last().push(mkLit(131, false));
			out_learnts.last().push(mkLit(132, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=19 &&
			assigns[266]==l_False &&
			assigns[267]==l_False &&
			assigns[268]==l_False &&
			assigns[269]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(266, false));
			out_learnts.last().push(mkLit(267, false));
			out_learnts.last().push(mkLit(268, false));
			out_learnts.last().push(mkLit(269, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=19 &&
			assigns[426]==l_False &&
			assigns[427]==l_False &&
			assigns[428]==l_False &&
			assigns[429]==l_False &&
			assigns[430]==l_False &&
			assigns[431]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(426, false));
			out_learnts.last().push(mkLit(427, false));
			out_learnts.last().push(mkLit(428, false));
			out_learnts.last().push(mkLit(429, false));
			out_learnts.last().push(mkLit(430, false));
			out_learnts.last().push(mkLit(431, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=19 &&
			assigns[597]==l_False &&
			assigns[598]==l_False &&
			assigns[599]==l_False &&
			assigns[600]==l_False &&
			assigns[601]==l_False &&
			assigns[602]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(597, false));
			out_learnts.last().push(mkLit(598, false));
			out_learnts.last().push(mkLit(599, false));
			out_learnts.last().push(mkLit(600, false));
			out_learnts.last().push(mkLit(601, false));
			out_learnts.last().push(mkLit(602, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=19 &&
			assigns[745]==l_False &&
			assigns[746]==l_False &&
			assigns[747]==l_False &&
			assigns[748]==l_False &&
			assigns[749]==l_False &&
			assigns[750]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(745, false));
			out_learnts.last().push(mkLit(746, false));
			out_learnts.last().push(mkLit(747, false));
			out_learnts.last().push(mkLit(748, false));
			out_learnts.last().push(mkLit(749, false));
			out_learnts.last().push(mkLit(750, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=20 &&
			assigns[133]==l_False &&
			assigns[134]==l_False &&
			assigns[135]==l_False &&
			assigns[136]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(133, false));
			out_learnts.last().push(mkLit(134, false));
			out_learnts.last().push(mkLit(135, false));
			out_learnts.last().push(mkLit(136, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=20 &&
			assigns[270]==l_False &&
			assigns[271]==l_False &&
			assigns[272]==l_False &&
			assigns[273]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(270, false));
			out_learnts.last().push(mkLit(271, false));
			out_learnts.last().push(mkLit(272, false));
			out_learnts.last().push(mkLit(273, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=20 &&
			assigns[432]==l_False &&
			assigns[433]==l_False &&
			assigns[434]==l_False &&
			assigns[435]==l_False &&
			assigns[436]==l_False &&
			assigns[437]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(432, false));
			out_learnts.last().push(mkLit(433, false));
			out_learnts.last().push(mkLit(434, false));
			out_learnts.last().push(mkLit(435, false));
			out_learnts.last().push(mkLit(436, false));
			out_learnts.last().push(mkLit(437, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=20 &&
			assigns[603]==l_False &&
			assigns[604]==l_False &&
			assigns[605]==l_False &&
			assigns[606]==l_False &&
			assigns[607]==l_False &&
			assigns[608]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(603, false));
			out_learnts.last().push(mkLit(604, false));
			out_learnts.last().push(mkLit(605, false));
			out_learnts.last().push(mkLit(606, false));
			out_learnts.last().push(mkLit(607, false));
			out_learnts.last().push(mkLit(608, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=20 &&
			assigns[751]==l_False &&
			assigns[752]==l_False &&
			assigns[753]==l_False &&
			assigns[754]==l_False &&
			assigns[755]==l_False &&
			assigns[756]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(751, false));
			out_learnts.last().push(mkLit(752, false));
			out_learnts.last().push(mkLit(753, false));
			out_learnts.last().push(mkLit(754, false));
			out_learnts.last().push(mkLit(755, false));
			out_learnts.last().push(mkLit(756, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=20 &&
			assigns[876]==l_False &&
			assigns[877]==l_False &&
			assigns[878]==l_False &&
			assigns[879]==l_False &&
			assigns[880]==l_False &&
			assigns[881]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(876, false));
			out_learnts.last().push(mkLit(877, false));
			out_learnts.last().push(mkLit(878, false));
			out_learnts.last().push(mkLit(879, false));
			out_learnts.last().push(mkLit(880, false));
			out_learnts.last().push(mkLit(881, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=21 &&
			assigns[137]==l_False &&
			assigns[138]==l_False &&
			assigns[139]==l_False &&
			assigns[140]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(137, false));
			out_learnts.last().push(mkLit(138, false));
			out_learnts.last().push(mkLit(139, false));
			out_learnts.last().push(mkLit(140, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=21 &&
			assigns[274]==l_False &&
			assigns[275]==l_False &&
			assigns[276]==l_False &&
			assigns[277]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(274, false));
			out_learnts.last().push(mkLit(275, false));
			out_learnts.last().push(mkLit(276, false));
			out_learnts.last().push(mkLit(277, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=21 &&
			assigns[438]==l_False &&
			assigns[439]==l_False &&
			assigns[440]==l_False &&
			assigns[441]==l_False &&
			assigns[442]==l_False &&
			assigns[443]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(438, false));
			out_learnts.last().push(mkLit(439, false));
			out_learnts.last().push(mkLit(440, false));
			out_learnts.last().push(mkLit(441, false));
			out_learnts.last().push(mkLit(442, false));
			out_learnts.last().push(mkLit(443, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=21 &&
			assigns[609]==l_False &&
			assigns[610]==l_False &&
			assigns[611]==l_False &&
			assigns[612]==l_False &&
			assigns[613]==l_False &&
			assigns[614]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(609, false));
			out_learnts.last().push(mkLit(610, false));
			out_learnts.last().push(mkLit(611, false));
			out_learnts.last().push(mkLit(612, false));
			out_learnts.last().push(mkLit(613, false));
			out_learnts.last().push(mkLit(614, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=21 &&
			assigns[757]==l_False &&
			assigns[758]==l_False &&
			assigns[759]==l_False &&
			assigns[760]==l_False &&
			assigns[761]==l_False &&
			assigns[762]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(757, false));
			out_learnts.last().push(mkLit(758, false));
			out_learnts.last().push(mkLit(759, false));
			out_learnts.last().push(mkLit(760, false));
			out_learnts.last().push(mkLit(761, false));
			out_learnts.last().push(mkLit(762, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=21 &&
			assigns[882]==l_False &&
			assigns[883]==l_False &&
			assigns[884]==l_False &&
			assigns[885]==l_False &&
			assigns[886]==l_False &&
			assigns[887]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(882, false));
			out_learnts.last().push(mkLit(883, false));
			out_learnts.last().push(mkLit(884, false));
			out_learnts.last().push(mkLit(885, false));
			out_learnts.last().push(mkLit(886, false));
			out_learnts.last().push(mkLit(887, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=22 &&
			assigns[141]==l_False &&
			assigns[142]==l_False &&
			assigns[143]==l_False &&
			assigns[144]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(141, false));
			out_learnts.last().push(mkLit(142, false));
			out_learnts.last().push(mkLit(143, false));
			out_learnts.last().push(mkLit(144, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=22 &&
			assigns[278]==l_False &&
			assigns[279]==l_False &&
			assigns[280]==l_False &&
			assigns[281]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(278, false));
			out_learnts.last().push(mkLit(279, false));
			out_learnts.last().push(mkLit(280, false));
			out_learnts.last().push(mkLit(281, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=22 &&
			assigns[444]==l_False &&
			assigns[445]==l_False &&
			assigns[446]==l_False &&
			assigns[447]==l_False &&
			assigns[448]==l_False &&
			assigns[449]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(444, false));
			out_learnts.last().push(mkLit(445, false));
			out_learnts.last().push(mkLit(446, false));
			out_learnts.last().push(mkLit(447, false));
			out_learnts.last().push(mkLit(448, false));
			out_learnts.last().push(mkLit(449, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=22 &&
			assigns[615]==l_False &&
			assigns[616]==l_False &&
			assigns[617]==l_False &&
			assigns[618]==l_False &&
			assigns[619]==l_False &&
			assigns[620]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(615, false));
			out_learnts.last().push(mkLit(616, false));
			out_learnts.last().push(mkLit(617, false));
			out_learnts.last().push(mkLit(618, false));
			out_learnts.last().push(mkLit(619, false));
			out_learnts.last().push(mkLit(620, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=22 &&
			assigns[763]==l_False &&
			assigns[764]==l_False &&
			assigns[765]==l_False &&
			assigns[766]==l_False &&
			assigns[767]==l_False &&
			assigns[768]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(763, false));
			out_learnts.last().push(mkLit(764, false));
			out_learnts.last().push(mkLit(765, false));
			out_learnts.last().push(mkLit(766, false));
			out_learnts.last().push(mkLit(767, false));
			out_learnts.last().push(mkLit(768, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=22 &&
			assigns[888]==l_False &&
			assigns[889]==l_False &&
			assigns[890]==l_False &&
			assigns[891]==l_False &&
			assigns[892]==l_False &&
			assigns[893]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(888, false));
			out_learnts.last().push(mkLit(889, false));
			out_learnts.last().push(mkLit(890, false));
			out_learnts.last().push(mkLit(891, false));
			out_learnts.last().push(mkLit(892, false));
			out_learnts.last().push(mkLit(893, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=23 &&
			assigns[145]==l_False &&
			assigns[146]==l_False &&
			assigns[147]==l_False &&
			assigns[148]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(145, false));
			out_learnts.last().push(mkLit(146, false));
			out_learnts.last().push(mkLit(147, false));
			out_learnts.last().push(mkLit(148, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=23 &&
			assigns[282]==l_False &&
			assigns[283]==l_False &&
			assigns[284]==l_False &&
			assigns[285]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(282, false));
			out_learnts.last().push(mkLit(283, false));
			out_learnts.last().push(mkLit(284, false));
			out_learnts.last().push(mkLit(285, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=23 &&
			assigns[450]==l_False &&
			assigns[451]==l_False &&
			assigns[452]==l_False &&
			assigns[453]==l_False &&
			assigns[454]==l_False &&
			assigns[455]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(450, false));
			out_learnts.last().push(mkLit(451, false));
			out_learnts.last().push(mkLit(452, false));
			out_learnts.last().push(mkLit(453, false));
			out_learnts.last().push(mkLit(454, false));
			out_learnts.last().push(mkLit(455, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=23 &&
			assigns[621]==l_False &&
			assigns[622]==l_False &&
			assigns[623]==l_False &&
			assigns[624]==l_False &&
			assigns[625]==l_False &&
			assigns[626]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(621, false));
			out_learnts.last().push(mkLit(622, false));
			out_learnts.last().push(mkLit(623, false));
			out_learnts.last().push(mkLit(624, false));
			out_learnts.last().push(mkLit(625, false));
			out_learnts.last().push(mkLit(626, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=23 &&
			assigns[769]==l_False &&
			assigns[770]==l_False &&
			assigns[771]==l_False &&
			assigns[772]==l_False &&
			assigns[773]==l_False &&
			assigns[774]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(769, false));
			out_learnts.last().push(mkLit(770, false));
			out_learnts.last().push(mkLit(771, false));
			out_learnts.last().push(mkLit(772, false));
			out_learnts.last().push(mkLit(773, false));
			out_learnts.last().push(mkLit(774, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=23 &&
			assigns[894]==l_False &&
			assigns[895]==l_False &&
			assigns[896]==l_False &&
			assigns[897]==l_False &&
			assigns[898]==l_False &&
			assigns[899]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(894, false));
			out_learnts.last().push(mkLit(895, false));
			out_learnts.last().push(mkLit(896, false));
			out_learnts.last().push(mkLit(897, false));
			out_learnts.last().push(mkLit(898, false));
			out_learnts.last().push(mkLit(899, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=23 &&
			assigns[1014]==l_False &&
			assigns[1015]==l_False &&
			assigns[1016]==l_False &&
			assigns[1017]==l_False &&
			assigns[1018]==l_False &&
			assigns[1019]==l_False &&
			assigns[1020]==l_False &&
			assigns[1021]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(1014, false));
			out_learnts.last().push(mkLit(1015, false));
			out_learnts.last().push(mkLit(1016, false));
			out_learnts.last().push(mkLit(1017, false));
			out_learnts.last().push(mkLit(1018, false));
			out_learnts.last().push(mkLit(1019, false));
			out_learnts.last().push(mkLit(1020, false));
			out_learnts.last().push(mkLit(1021, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=24 &&
			assigns[149]==l_False &&
			assigns[150]==l_False &&
			assigns[151]==l_False &&
			assigns[152]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(149, false));
			out_learnts.last().push(mkLit(150, false));
			out_learnts.last().push(mkLit(151, false));
			out_learnts.last().push(mkLit(152, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=24 &&
			assigns[286]==l_False &&
			assigns[287]==l_False &&
			assigns[288]==l_False &&
			assigns[289]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(286, false));
			out_learnts.last().push(mkLit(287, false));
			out_learnts.last().push(mkLit(288, false));
			out_learnts.last().push(mkLit(289, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=24 &&
			assigns[456]==l_False &&
			assigns[457]==l_False &&
			assigns[458]==l_False &&
			assigns[459]==l_False &&
			assigns[460]==l_False &&
			assigns[461]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(456, false));
			out_learnts.last().push(mkLit(457, false));
			out_learnts.last().push(mkLit(458, false));
			out_learnts.last().push(mkLit(459, false));
			out_learnts.last().push(mkLit(460, false));
			out_learnts.last().push(mkLit(461, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=24 &&
			assigns[627]==l_False &&
			assigns[628]==l_False &&
			assigns[629]==l_False &&
			assigns[630]==l_False &&
			assigns[631]==l_False &&
			assigns[632]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(627, false));
			out_learnts.last().push(mkLit(628, false));
			out_learnts.last().push(mkLit(629, false));
			out_learnts.last().push(mkLit(630, false));
			out_learnts.last().push(mkLit(631, false));
			out_learnts.last().push(mkLit(632, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=24 &&
			assigns[775]==l_False &&
			assigns[776]==l_False &&
			assigns[777]==l_False &&
			assigns[778]==l_False &&
			assigns[779]==l_False &&
			assigns[780]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(775, false));
			out_learnts.last().push(mkLit(776, false));
			out_learnts.last().push(mkLit(777, false));
			out_learnts.last().push(mkLit(778, false));
			out_learnts.last().push(mkLit(779, false));
			out_learnts.last().push(mkLit(780, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=24 &&
			assigns[900]==l_False &&
			assigns[901]==l_False &&
			assigns[902]==l_False &&
			assigns[903]==l_False &&
			assigns[904]==l_False &&
			assigns[905]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(900, false));
			out_learnts.last().push(mkLit(901, false));
			out_learnts.last().push(mkLit(902, false));
			out_learnts.last().push(mkLit(903, false));
			out_learnts.last().push(mkLit(904, false));
			out_learnts.last().push(mkLit(905, false));
printf("out_learnt "), printclause(out_learnts.last());
}
		if(mlen>=24 &&
			assigns[1022]==l_False &&
			assigns[1023]==l_False &&
			assigns[1024]==l_False &&
			assigns[1025]==l_False &&
			assigns[1026]==l_False &&
			assigns[1027]==l_False &&
			assigns[1028]==l_False &&
			assigns[1029]==l_False &&
1) {
			out_learnts.push();
			out_learnts.last().push(mkLit(1022, false));
			out_learnts.last().push(mkLit(1023, false));
			out_learnts.last().push(mkLit(1024, false));
			out_learnts.last().push(mkLit(1025, false));
			out_learnts.last().push(mkLit(1026, false));
			out_learnts.last().push(mkLit(1027, false));
			out_learnts.last().push(mkLit(1028, false));
			out_learnts.last().push(mkLit(1029, false));
printf("out_learnt "), printclause(out_learnts.last());
}
